name: Front-end CI

on:
  push:
    branches: [main, dev]
    paths:
      - 'app/front-end/**'
  pull_request:
    branches: [main, dev]
    paths:
      - 'app/front-end/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/front-end
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './app/front-end/package-lock.json'
      
      - name: Install dependencies
        run: npm ci

      - name: Check Code Linting
        run: npm run lint --if-present

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/front-end
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './app/front-end/package-lock.json'
      
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test --if-present